### ISSUE TITLE
documentation is really hard to understand

### ISSUE THREAD

**Issue by eliot1785** [googleapis/python-secret-manager#175]
Hi, I created a support request with Google since I have paid support, but they actually told me to come here (both sides have now told me to speak with the other side). 

I had a lot of difficulty understanding the library documentation. Here are some of the issues I ran into... I hope this doesn't read too negatively, but you should know that it's quite difficult for a new user to understand.

Issues all relate to the following page: https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/secret_manager_service.html

1) The signatures seem to be written in a special kind of definition language that isn't familiar to me. Is this language defined anywhere? If so it would be great if you could link to it from the documentation. My inability to fully understand these signatures is blocking me from using the library.

For example, from the instantiator, what does Union[str, google.cloud.secretmanager_v1.services.secret_manager_service.transports.base.SecretManagerServiceTransport] mean? I'm guessing it means you can provide either a string or that object, because it doesn't seem like it could actually be the "union" of the two. But I don't know where to look for the definition of Union.

This one is more confusing (again from the instantiator):
client_options: <module 'google.api_core.client_options' from '/workspace/.nox/docs/lib/python3.8/site-packages/google/api_core/client_options.py'> = None

I can't figure this one out at all. I assume we aren't meant to pass a Python module as an argument, but I wouldn't be confident using this argument even if I could find a class in that path that seemed to match. 

2. In both of the above cases, you aren't linking to the class definition (SecretManagerServiceTransport or whatever the class is supposed to be in the second example), so I wouldn't know how to instantiate the class in any case.

3. There isn't any example code provided for anything, which would make things a lot easier.

4. You list a few methods on these pages that look like they're probably "private" methods, like "parse_secret_path". It seems like it would make things simpler if you hid whatever you don't intend end users to use.

Just in general, I've found the Python Cloud Client Library docs to be hard to understand. Not enough examples in particular, which is especially important since sometimes they can be pretty complex.

**Comment by busunkim96** [comment]
Hi @eliot1785,

Thanks for taking the time to leave feedback.

If you're a new user of any Google Cloud product, you should start off by cloud.google.com. For Secret Manager, that's https://cloud.google.com/secret-manager/docs. These pages have (1) conceptual documentation and (2) code samples to accomplish common tasks. Most products have a quickstart to help you get started: https://cloud.google.com/secret-manager/docs/quickstart 

The reference documentation (https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/) is an exhaustive list of every function/type inside the library. It's primary purpose is for looking up specific options after you're already familiar with the API.

> The signatures seem to be written in a special kind of definition language that isn't familiar to me. Is this language defined anywhere? If so it would be great if you could link to it from the documentation. My inability to fully understand these signatures is blocking me from using the library.

I think the section you're referring is this:
![image](https://user-images.githubusercontent.com/8822365/128207363-1a4141ed-bae7-4bd4-82d7-41e8c9f2d7fe.png)

That is a copy-paste of the function definition (some replacements since the source code aliases some imports). It's primary purpose is figuring out whether something is a positional or keyword argument. The parameters themselves are described below in more detail.

https://github.com/googleapis/python-secret-manager/blob/e949b6a56815079d1ffd25d76cbee63cb4a79390/google/cloud/secretmanager_v1/services/secret_manager_service/client.py#L272-L279


> For example, from the instantiator, what does Union[str, google.cloud.secretmanager_v1.services.secret_manager_service.transports.base.SecretManagerServiceTransport] mean? I'm guessing it means you can provide either a string or that object, because it doesn't seem like it could actually be the "union" of the two. But I don't know where to look for the definition of Union.

This syntax is used when the argument can be passed as one type or another. See [typing.Union](https://docs.python.org/3/library/typing.html#typing.Union). For this case, it means the argument can be a str OR a `google.cloud.secretmanager_v1.services.secret_manager_service.transports.base.SecretManagerServiceTransport`. 

> This one is more confusing (again from the instantiator):
> client_options: <module 'google.api_core.client_options' from '/workspace/.nox/docs/lib/python3.8/site-packages/google/api_core/client_options.py'> = None

Ah, I think that specifically needs a fix that's already been applied to the sync client. See [here](https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/secret_manager_service.html#google.cloud.secretmanager_v1.services.secret_manager_service.SecretManagerServiceClient) for what the AsyncClient should look like once that's been fixed. 

One other important note: if the parameter/argument is a keyword argument and the docstring doesn't say **Required** it is optional. You can instantiate clients with 0 arguments in most cases.

```py
# Import the Secret Manager client library.
from google.cloud import secretmanager

# Create the Secret Manager client.
client = secretmanager.SecretManagerServiceClient()
```

> I can't figure this one out at all. I assume we aren't meant to pass a Python module as an argument, but I wouldn't be confident using this argument even if I could find a class in that path that seemed to match.
> 
> In both of the above cases, you aren't linking to the class definition (SecretManagerServiceTransport or whatever the class is supposed to be in the second example), so I wouldn't know how to instantiate the class in any case.
> 

Fair point, let's think about whether we want to publish the transport docs @parthea. It's pretty uncommon to need to use instantiate a transport separately, as the client instantiated one works fine for most use cases.

Another point worth mentioning is that the generated reference docs are derived from the source code docstrings. If you need to create a transport please reference the docstrings in the [source code](https://github.com/googleapis/python-secret-manager/tree/master/google/cloud/secretmanager_v1/services/secret_manager_service/transports). 

> There isn't any example code provided for anything, which would make things a lot easier.

We're working on adding some generic generated sample code inside the docstrings right now. (ETA is this quarter). But even after those are published Secret Manager has high quality handwritten [samples](https://cloud.google.com/secret-manager/docs/samples) that accompany how-to guides. 

> You list a few methods on these pages that look like they're probably "private" methods, like "parse_secret_path". It seems like it would make things simpler if you hid whatever you don't intend end users to use.

Can you share why those seemed like private methods to you? Those methods are intended to be public - the `secret` is terminology specific to this API. Private functions/attributes start with a `_`:
https://github.com/googleapis/python-secret-manager/blob/e949b6a56815079d1ffd25d76cbee63cb4a79390/google/cloud/secretmanager_v1/services/secret_manager_service/client.py#L54-L58. We're following the [Google Style Guide](https://google.github.io/styleguide/pyguide.html#3162-naming-conventions) here, but I believe it's fairly common in Python codebases to use the leading `_` as "private by convention". 

> Just in general, I've found the Python Cloud Client Library docs to be hard to understand. Not enough examples in particular, which is especially important since sometimes they can be pretty complex.

The reference docs on googleapis.dev aren't meant as the starting point for you to get acquainted with the product - https://cloud.google.com/secret-manager/docs/how-to is where you should start out. 😄  If you don't mind, could you share how you ended up on the reference doc pages? That could help us design a more helpful getting started experience for folks.

CC @dandhlee - Some of this information might be interesting since you're working on the new ref docs.

**Comment by dandhlee** [comment]
Thank you for the ping Bu Sun! And thank you as well @eliot1785 for bringing this to our attention. 

I've been working on a lot of customer issues lately and one of the most frequent topics brought up is "I'm new, I'm on this doc and it makes no sense". Similarly, Bu Sun's point on that the page you ended up on is not the most appropriate place if you're new - I definitely agree with, however we should also put in the effort to specify the difficulty as users are not aware of this. Tricky part is finding where to redirect the users to, and being able to do this throughout our documentation - there's 100+ client libraries I'm working with for the new ref docs, totalling to 10k+ pages.

> The signatures seem to be written in a special kind of definition language that isn't familiar to me. Is this language defined anywhere? If so it would be great if you could link to it from the documentation. My inability to fully understand these signatures is blocking me from using the library.

I will personally agree with you on this, because even to this day a function signature with 7+ lines full of text at first glance still scares me. There are explanations provided below that goes into depth for each provided argument, but I'll keep this in mind when attempting to show the full signature.

**Comment by eliot1785** [comment]
Hi folks, thanks for your response, it was encouraging.

It's a bit embarrassing, but I had never thought to click on the Samples tab at the top of the main documentation pages. That page is excellent and contains more or less what I was looking for.

I think the main problem is that the current documentation pushes you toward googleapis.dev pretty quickly. It isn't exactly buried and you get the impression that that's the place to go to learn how to use the API. Below are some of my series of clicks if that helps you understand how I arrived here. 

For example once I realized that I wanted to use Google Cloud Client Libraries, I believe the flow was something like:
- Google "Google Cloud Client Libraries"
- Arrive at main page for the libraries (this is the top Google result): https://cloud.google.com/apis/docs/cloud-client-libraries
- Incidentally on this page it says that these links are for getting started: "The following table provides links to get you started with Cloud Client Libraries in all our currently supported languages."
- Both of the links for Python take you to GitHub
- Scroll down to Secret Manager and click on it
- It links directly to googleapis.dev for documentation

Another flow I remember doing:
- Go to main How To guide: https://cloud.google.com/secret-manager/docs/how-to
- Click on "Accessing the API" to reach: https://cloud.google.com/secret-manager/docs/accessing-the-api
- Click on "Secret Manager Client Libraries" to reach: https://cloud.google.com/secret-manager/docs/reference/libraries
- Scroll down to "Using the client library," read a very tiny code snippet, and then be told by the documentation that for more information I need to go to googleapis.dev

Anyway, now that I've fixed my brain fart about how to find things in the main documentation, I have a bit of a different perspective. Perhaps a simple thing you could do for now is just link to the Samples page from googleapis.dev and say that that is better if you're new to the API, and that googleapis.dev is only for experts.

If I were you I wouldn't really want to duplicate all of the documentation if there's already pretty nice code samples in the main documentation, although the look and feel of googleapis.dev could still be improved.

**Comment by eliot1785** [comment]
Forgot to mention, as for my not understanding things like Union etc - I discovered just now that that's associated with the Python `typing` module. I've been using Python for a couple years but hadn't yet encountered any library that specified its parameters that way, from my experience it's somewhat uncommon. Don't get me wrong, it might be an improvement to have that, but it might not hurt to add a comment noting that you're using that library to format the docs, along with a link to the `typing` docs. (Of course it all comes back to what audience you intend.)
