### ISSUE TITLE
Client library call to gRPC hangs indefinitely under some conditions

### ISSUE THREAD

**Issue by fergusmac** [googleapis/python-secret-manager#184]
I have a Django application running on Apache on a GCE Ubuntu VM. I have a service account with the Secret Manager Admin permission, and I am loading its credentials via GOOGLE_APPLICATION_CREDENTIALS. I've verified that the credentials are loaded by the client library successfully. 

When I make any request via the secret manager client library, my application hangs indefinitely - the call never returns.

Strangely, the issue does not occur when I run the code using the Django dev server instead of Apache in the same environment, even when Apache is running as the same user.

I traced the execution as far as grpc._channel line 929

```
class _UnaryUnaryMultiCallable(grpc.UnaryUnaryMultiCallable):...
  def _blocking(...
    call = self._channel.segregated_call(...

# e.g. called from google.cloud.secretmanager_v1.services.secret_manager_service.client.SecretManagerServiceClient.list_secret_versions L971
```

I believe this calls into the C gRPC code. This never returns. As far as I can see, all the arguments passed in to this call are the same between the two scenarios.

I turned on the logging for gRPC. Things look good when using the Django dev server:

```
secure_channel_create.cc:178] grpc_secure_channel_create(creds=0x17cfda0, target=secretmanager.googleapis.com:443, args=0x7fe254620f20, reserved=(nil))
init.cc:167]                grpc_init(void)
client_channel.cc:1099]     chand=0x2299b88: creating client_channel for channel stack 0x2299b18
...
timer_manager.cc:188]       sleep for a 1001 milliseconds
...
client_channel.cc:1879]     chand=0x2299b88 calld=0x229e440: created call
...
call.cc:1980]               grpc_call_start_batch(call=0x229daa0, ops=0x20cfe70, nops=6, tag=0x7fe25463c680, reserved=(nil))
call.cc:1573]               ops[0]: SEND_INITIAL_METADATA...
call.cc:1573]               ops[1]: SEND_MESSAGE ptr=0x21f7a20
...
```

but under Apache, it creates the client_channel, then just sits there - no call is created or run:

```
secure_channel_create.cc:178] grpc_secure_channel_create(creds=0x7fd5bc850f70, target=secretmanager.googleapis.com:443, args=0x7fd583065c50, reserved=(nil))
init.cc:167]                grpc_init(void)
client_channel.cc:1099]     chand=0x7fd5bca91bb8: creating client_channel for channel stack 0x7fd5bca91b48
...
timer_manager.cc:188]       sleep for a 1001 milliseconds
...
timer_manager.cc:188]       sleep for a 1001 milliseconds
...
etc
```

#### Environment details

  - OS type and version: Ubuntu 21.04 (GNU/Linux 5.11.0-1017-gcp x86_64)
  - Python version: Python 3.9.5
  - pip version: 20.3.4
  - `google-cloud-secret-manager` version: 2.7.0
  - Apache: 2.4.46 (Ubuntu)

#### Steps to reproduce

1. Install Apache
2. Install mod_wsgi, and point Apache to a Python WSGI application.
3. Have your WSGI application make any request via the secret manager client library.
4. Start Apache, visit page

#### Code example

```python
secret_name = f"projects/{project_id}/secrets/foo"
client = secretmanager.SecretManagerServiceClient()
client.list_secret_versions(parent=secret_name)
```

**Comment by busunkim96** [comment]
Hi @fergusmac,

Sorry to hear you're having trouble. Thank you for the detailed log and code example!

Have you ever successfully made a request to another google cloud client library using a similar setup? If not, please try this [code sample](https://cloud.google.com/storage/docs/listing-buckets#code-samples) that lists buckets in Google Cloud Storage. Since `google-cloud-storage` makes calls to the REST API, being able to run this sample might indicate something going wrong with gRPC specifically.

If the above doesn't work, please try this snippet. It detects the service account from the environment and refreshes it to get a token. (The library will usually do this for you when the first request is ent).
```py
import google.auth
import google.auth.transport

credentials, _ = google.auth.default()
credentials.refresh(google.auth.transport.requests.Request())
```

I also see you opened https://stackoverflow.com/questions/68933205/why-does-this-grpc-call-from-the-google-secret-manager-api-hang-when-run-by-apac, I'll leave the link here in case it's helpful for other folks debugging the issue.

**Comment by fergusmac** [comment]
Hi,

Thanks for taking a look and your suggestions. I ended up deducing that the problem is that Apache's forking causes an issue for gRPC. Please see the stack overflow page linked for further details.
