### ISSUE TITLE
[Question] Do we need to close the SecretManagerServiceClient?

### ISSUE THREAD

**Issue by ZackTherrien** [googleapis/python-secret-manager#297]
In other packages (ex. PHP) we need to manually close the SecretManagerServiceClient, however in this Python package there is no close method, only a `__exit__()`. 

When should this be used?

Example:
```
try:
     client = SecretManagerServiceClient()
except Exception as ex:
     raise SecretServiceException('create_client', str(ex))

try:
     self.load_all_secrets(client, gcp_project_id)
except Exception as ex:
     raise SecretServiceException('list_secrets', str(ex))
finally:
     # should we close the client at some point?
```

Thanks

**Comment by parthea** [comment]
Hi Zack, 

The client doesn't have a `close` method however since `__exit__` is defined you'll be able to use a `with` [statement](https://peps.python.org/pep-0343/) and have resources cleaned up without using `try/finally`.

```
with bigquery_datatransfer_v1.DataTransferServiceClient() as client:
     self.load_all_secrets(client, gcp_project_id)
```

I'm going to close this issue but please feel free to re-open it if you have additional questions.
