### ISSUE TITLE
Unpythonic API

### ISSUE THREAD

**Issue by 1oglop1** [googleapis/python-secret-manager#66]
Hello, I'm creating this issue just out of pure frustration.
Honestly, I'm running into too many issues just trying to initialize objects. 

If I use this example (first google result on: GCP Secret Manager python) https://cloud.google.com/secret-manager/docs/reference/libraries#client-libraries-usage-python

and copy it into pycharm, methods get flagged for using the wrong type.

![image](https://user-images.githubusercontent.com/7480694/102402300-e1e66c00-3fe4-11eb-88c3-ec9a271129a6.png)

And that's very confusing on top of that I import the required object, it's signature requires some magical parameter "mapping" described nowhere.
```
from google.cloud.secretmanager_v1.types import CreateSecretRequest
req = CreateSecretRequest()
```
![image](https://user-images.githubusercontent.com/7480694/102402525-312c9c80-3fe5-11eb-808f-0b7ce4ef35e3.png)

So it's even more confusing that some objects can be instantiated from a pure dictionary like the example suggests.

The other day I tried to instantiate `CloudBuildSubmitRequest` and the dictionary I passed to the object had to be partially from the appropriate types and partially `key<str>:val<str>` or nested dicts.

It took me good 30 minutes to instantiate 1 object.

I wish there is some solution under the development because this is literaly the worst python API of all cloud clients.

**Comment by busunkim96** [comment]
Hi @1oglop1,

Sorry to hear you're having trouble, and thank you for taking the time to leave feedback.

> If I use this example (first google result on: GCP Secret Manager python) https://cloud.google.com/secret-manager/docs/reference/libraries#client-libraries-usage-python and copy it into pycharm, methods get flagged for using the wrong type.

The API methods allow a request to be provided as (1) a dict or (2) a library type. The type annotations incorrectly show that only the class instance can be passed, so pycharm is raising an error. I've filed https://github.com/googleapis/gapic-generator-python/issues/715 to track that.

To avoid the errors, you can use the library provided message types instead. Here is the sample you linked rewritten with `secretmanager.CreateSecretRequest`.

```py
# Import the Secret Manager client library.
from google.cloud import secretmanager

# GCP project in which to store secrets in Secret Manager.
project_id = "YOUR_PROJECT_ID"

# ID of the secret to create.
secret_id = "YOUR_SECRET_ID"

# Create the Secret Manager client.
client = secretmanager.SecretManagerServiceClient()

# Build the parent name from the project.
parent = f"projects/{project_id}"

secret = secretmanager.Secret(
        replication=secretmanager.Replication(automatic=secretmanager.Replication.Automatic())
)
request = secretmanager.CreateSecretRequest(
    parent=parent,
    secret_id=secret_id,
    secret=secret,
)

# Create the parent secret.
secret = client.create_secret(request)

```

> And that's very confusing on top of that I import the required object, it's signature requires some magical parameter "mapping" described nowhere.

It looks like because of the way the classes are defined pycharm isn't providing assistance on the attributes. You can reference the docstring or our [published documentation](https://googleapis.dev/python/secretmanager/latest/secretmanager_v1/types.html#google.cloud.secretmanager_v1.types.CreateSecretRequest) for attributes on each of the instance methods.

https://github.com/googleapis/python-secret-manager/blob/dee9bd0ee381528476e8f6f1755b713238b1f1be/google/cloud/secretmanager_v1beta1/types/service.py#L103-L122

**Comment by meredithslota** [comment]
The linked issue https://github.com/googleapis/gapic-generator-python/issues/715 has been marked resolved, so I'm closing this out based on the comment above — please do file a new issue if you're still encountering issues. Thanks!
